language: php
dist: bionic

services:
  - postgres

sudo: required

addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10

php:
  - 7.1

env:
  BASE_URL="http://localhost/tripal4/web" && SIMPLETEST_BASE_URL="http://localhost/tripal4/web" &&
  SIMPLETEST_DB=pgsql://tripaladmin:tripal4developmentonlylocal@localhost/tripal4_dev &&
  BROWSER_OUTPUT_DIRECTORY=tripal4/web/sites/default/simpletest

before_install:
  - psql --command="CREATE USER tripaladmin WITH PASSWORD 'tripal4developmentonlylocal'" -U postgres
  - psql --command="CREATE DATABASE tripal4_dev WITH OWNER tripaladmin" -U postgres

install:
  - composer create-project drupal-composer/drupal-project:8.x-dev tripal4 --stability dev --no-interaction
  - drush site-install standard \
    --db-url=pgsql://tripaladmin:tripal4developmentonlylocal@localhost/tripal4_dev \
    --account-mail="tripaladmin@localhost" \
    --account-name=tripaladmin \
    --account-pass=some_admin_password \
    --site-mail="tripaladmin@localhost" \
    --site-name="Tripal 4 Development"
