tripal.bio_data.*:
  type: config_entity
  label: 'Tripal Content Type'
  mapping:
    id:
      type: integer
      label: 'ID'
    name:
      type: string
      label: 'Name'
    label:
      type: label
      label: 'Label'
    term_id:
      type: integer
      label: 'Term ID'
    help_text:
      type: text
      label: 'Help Text'
